@startuml

interface House
interface HouseBuilder
class CommonHouse
class HighHouse
class HouseDirector
class Client

HouseBuilder : +house:House
HouseBuilder : +buildBasic()
HouseBuilder : +buildWalls()
HouseBuilder : +getResult():House

CommonHouse : +buildBasic()
CommonHouse : +buildWalls()
CommonHouse : +getResult():House
HighHouse : +buildBasic()
HighHouse : +buildWalls()
HighHouse : +getResult():House

HouseDirector : -builder:HouseBuilder
HouseDirector : +constructHouse():House

HouseBuilder <|.. CommonHouse
HouseBuilder <|.. HighHouse

HouseBuilder *-- House
HouseBuilder --o HouseDirector

HouseDirector <.. Client
CommonHouse <.. Client
HighHouse <.. Client


@enduml