@startuml

abstract Mediator
abstract Colleague
class ConcreteMediator
class ConcreteColleague

Mediator <|-- ConcreteMediator
Colleague <|-- ConcreteColleague

Mediator -- Colleague

Mediator : +Register()
Mediator : +GetMessage()
Mediator : +SendMessage()

Colleague : +SendMessage()


ConcreteMediator : -colleagues:HashMap
Colleague : +getMediator(): Mediator



@enduml